experiment:
  name: allelopathic_harvest
  epochs: 100
  max_turns: 300
  epsilon_decay: 0.0001
  record_period: 10

world:
  height: 31
  width: 32
  layers: 3
  default_object: EmptyEntity
  full_mdp: False
  mode: DEFAULT
  
  total_berries: 348
  allelopathic_constant: 0.000005
  
  red_preference_count: 8
  green_preference_count: 8
  blue_preference_count: 0
  
  preferred_berry_reward: 2
  other_berry_reward: 1

model:
  iqn:
    type: iRainbowModel
    parameters:
      layer_size: 250
      n_step: 3
      batch_size: 64
      memory_size: 1024
      LR: 0.00025
      TAU: .001
      GAMMA: 0.99
      n_quantiles: 12
      sync_freq: 200
      model_update_freq: 4
      epsilon: 0.8
      device: cpu
  epsilon_decay: 0.0001

agent:
  agent:
    num: 16
    model: iqn
    beam_radius: 1
    rotation: True
    obs:
      channels: 11
      vision: 5
      n_frames: 5
      embeddings: 3

root: '~/Documents/GitHub/sorrel'
log: False